version: 2.1

jobs:

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest tests/ -v

  check-submission:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Assignment Checker
          command: python checker/generate_report.py
      - run:
          name: Show results
          command: cat dashboard/results.json
      - persist_to_workspace:
          root: .
          paths:
            - dashboard/results.json

  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t "$DOCKER_USERNAME/assignment-checker:latest" .
            docker push "$DOCKER_USERNAME/assignment-checker:latest"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to Render
          command: curl -X POST $RENDER_DEPLOY_HOOK_URL

  notify:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: pip install requests -q
      - run:
          name: Send Notifications
          command: python notify.py

workflows:
  assignment-pipeline:
    jobs:
      - test
      - check-submission:
          requires:
            - test
      - build-and-push:
          requires:
            - check-submission
      - deploy:
          requires:
            - build-and-push
      - notify:
          requires:
            - deploy